name: Installer test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.editorconfig'

jobs:
  test:
    name: "Test on ${{ matrix.os }} (Docker)"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install bashunit
      run: |
        curl -s https://bashunit.typeddevs.com/install.sh | bash

    - name: Run the tests
      env:
        SCRIPT_FILE: 'start-local.sh'
        TEST_CONTAINER_CLI: docker
      run: |
        ./lib/bashunit

  test-podman:
    name: "Test on ${{ matrix.os }} (Podman)"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install bashunit
      run: |
        curl -s https://bashunit.typeddevs.com/install.sh | bash
   
    - name: Set up Podman
      run: |
        sudo snap remove docker
        sudo apt-get remove -y docker docker-engine docker.io containerd runc docker-ce docker-ce-cli
        sudo apt-get -y install podman

    - name: Run the tests
      env:
        SCRIPT_FILE: 'start-local-podman.sh'
        TEST_CONTAINER_CLI: podman
      run: |
        ./lib/bashunit
